cc_binary(
    name = "test_ldlt",
    srcs = ["test_ldlt.cpp"],
    # deps = ["//algorithms:optimizer_base", 
    #         "//algorithms:optimizer_descent",
    #         "//algorithms:optimizer_newton",
    #         "//objectivefunction:function_himmelblau",
    #         "//objectivefunction:function_mccormick",
    #         "//objectivefunction:function_quadratic",
    # ],
)