cc_binary(
    name = "test_function",
    srcs = ["test_function.cpp"],
    deps = ["//objectivefunction:function_base",
            "//objectivefunction:function_convex3d",
            "//objectivefunction:function_scalar",
            "//objectivefunction:function_quadratic",
            "//objectivefunction:function_himmelblau",
            "//objectivefunction:function_mccormick",
            "//objectivefunction:function_rosenbrock",
    ],
)
