cc_binary(
    name = "test_function",
    srcs = ["test_function.cpp"],
    deps = ["//objectivefunction:function_base", 
    "//objectivefunction:function_example", 
    "//objectivefunction:function_quadratic", 
    "//objectivefunction:function_himmelblau",
    ],
)